# Generated by Django 4.1.4 on 2023-12-30 19:50

import agenda.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', agenda.manager.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='teve_covid',
            new_name='apto_agendamento',
        ),
    ]
