# Generated by Django 4.1.4 on 2024-01-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_estabelecimento_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
