# Generated by Django 4.1.4 on 2024-01-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
